/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Connections": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "socket": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
    "web": {
      "type": "sst.aws.Nuxt"
      "url": string
    }
  }
}
